Feature/implementClientModule
pavloshumylo/4square pull request #3
Opened 2018-06-12 20:54 UTC by pavloshumylo

2018-06-13 20:10 UTC, serg1236 requested changes

2018-06-13 20:10 UTC, serg1236 commented on client/src/main/java/com/foursquare/Application.java
> +    public static void main(String[] args) {
Client is a library. Its ok to create app for manual testing but not ok for production.

2018-06-13 20:10 UTC, serg1236 commented on client/src/main/java/com/foursquare/endpoints/FoursquareClientEndpoints.java
> +    CompletableFuture<ResponseEntity<List<Venue>>> invokeGetEndpoint(String accessToken);
No response entities. Body should be unwrapped inside of the client.

2018-06-13 20:10 UTC, serg1236 commented on client/src/main/java/com/foursquare/endpoints/FoursquareClientEndpoints.java
> +    CompletableFuture<ResponseEntity<List<Venue>>> invokeGetEndpoint(String accessToken);
Think about other ways to pass the access token. (ITS NOT AN ISSUE, JUST THINK:)

2018-06-13 20:10 UTC, serg1236 commented on client/src/main/java/com/foursquare/endpoints/impl/FoursquareClientEndpointsImpl.java
> +    @Value("${foursquare.endPointHost:http://localhost:8080/}")
If you use protocol here, it is not a host already, it is base url or something like that.

2018-06-13 20:10 UTC, serg1236 commented on client/src/main/java/com/foursquare/endpoints/impl/FoursquareClientEndpointsImpl.java
> +    @Value("${foursquare.endPointHost:http://localhost:8080/}")
And I would not put the trailing slash here:)

2018-06-13 20:10 UTC, serg1236 commented on client/src/main/java/com/foursquare/endpoints/impl/FoursquareClientEndpointsImpl.java
> +            public void onSuccess(T result) { completable.complete(result); }
It will be `result.getBody()` after you fix the interface.

2018-06-13 20:10 UTC, serg1236 commented on client/src/main/java/com/foursquare/endpoints/impl/FoursquareClientEndpointsImpl.java
> +        CompletableFuture<T> completable = new CompletableFuture<T>();
Implement `onCancel` for the CompletableFuture. It should cancel Listenable one.

2018-06-13 20:10 UTC, serg1236 commented on client/src/main/java/com/foursquare/endpoints/impl/FoursquareClientEndpointsImpl.java
> +    public void setHost(String host) {
We shouldn't give ability to change it.

2018-06-13 20:10 UTC, serg1236 commented on client/src/main/resources/application.yml
> +  port: ${SERVER_PORT:8080}
why do you need this? Isn't 8080 default?

2018-06-13 20:10 UTC, serg1236 commented on client/src/main/java/com/foursquare/endpoints/FoursquareClientEndpoints.java
> +public interface FoursquareClientEndpoints {
`ClientEndpoints` means "endpoints of the client" which is at least strange:) It's just a `FoursquareClient`.

2018-06-13 20:10 UTC, serg1236 commented on client/src/test/java/com/foursquare/endpoints/FoursquareClientEndpointsImplTest.java
> +        foursquareClientEndpoints.setHost("http://localhost:"+wireMockRule.port()+"/");
Aha...that's why you need `setHost`. We should not add extra methods just to test easier. But I agree it is not simple to pass the dynamic port. There is a way to pass it to properties but it is not simple... For now just use `org.springframework.util.ReflectionUtils`

2018-06-13 20:10 UTC, serg1236 commented on client/src/test/java/com/foursquare/endpoints/FoursquareClientEndpointsImplTest.java
> +        InputStream inputStreamWithSearchResponseDtoSecond = getClass().getClassLoader()
No need to load it twice. Use one only.

2018-06-13 20:10 UTC, serg1236 commented on client/src/test/java/com/foursquare/endpoints/FoursquareClientEndpointsImplTest.java
> +package com.foursquare.endpoints;
We'll also need tests for `onCancel` and negative tests.

2018-06-18 18:26 UTC, serg1236 requested changes
Two comments. Try to create a better test and fix the naming.

2018-06-18 18:26 UTC, serg1236 commented on client/src/main/java/com/foursquare/endpoints/FoursquareClient.java
> +    CompletableFuture<List<Venue>> invokeGetEndpoint(String accessToken);
This naming (my bad, I missed it) makes me cry. Imagine that you are a user of this service. You inject the client to your service and go inside to see what you can do. And what do you see? invokeBlahEndpoint, invokeBlahBlahEndpoint, ... And you like: "WTF? Why do I need to invoke something? What will it cause? What I delete if I invoke delete endpoint? Or I do not delete anything?".

2018-06-18 18:26 UTC, serg1236 commented on client/src/main/java/com/foursquare/endpoints/FoursquareClient.java
> +    CompletableFuture<List<Venue>> invokeGetEndpoint(String accessToken);
Try to use simple names. Same as you use on a service layers (maybe with some additional details). For instance: "registerNewUser", "registerUser", "removeVenue", "getAllVenues", "getAllVenuesForUser" etc.

2018-06-18 18:26 UTC, serg1236 commented on client/src/test/java/com/foursquare/endpoints/FoursquareClientImplTest.java
> +    public void testbuildCompletableFuture_Cancel_ShouldThrowCancellationException() throws InterruptedException, ExecutionException {
Are we able to check somehow if ListenableFuture was canceled also?

2018-06-21 16:20 UTC, sdakhnii-eagle approved these changes

2018-06-21 16:21 UTC, merged